/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahba;

import connection.AccionesTablaAlumnoCursaMateria;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class Alta extends javax.swing.JFrame {

    Object[][] data = null;
    /**
     * Creates new form Alta
     */
    public Alta() {
        initComponents();
        DefaultComboBoxModel modelComboBoxAcademias = new DefaultComboBoxModel(AccionesTablaAlumnoCursaMateria.getListaAcademias());
        comboBoxAcademia.setModel(modelComboBoxAcademias);
        DefaultComboBoxModel modelComboBoxCarreras = new DefaultComboBoxModel(AccionesTablaAlumnoCursaMateria.getListaCarreras());
        comboBoxCarrera.setModel(modelComboBoxCarreras);
        comboBoxCarreras2.setModel(modelComboBoxCarreras);
        getStatics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoApellidoPaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoApellidoMaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoBoleta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBoxCarrera = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        campoUnidadDeAprendizaje = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboBoxAcademia = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboBoxCarreras2 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelBionicos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelMecatronicos = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelTelematicos = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        comboBoxConsulta = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelMatricula = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelPorcentaje = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelISISA = new javax.swing.JLabel();
        comboBoxDiscrimina = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        comboBoxDiscrimina2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        botonActualizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNombreKeyTyped(evt);
            }
        });

        jLabel2.setText("Apellido Paterno: ");

        campoApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoApellidoPaternoKeyTyped(evt);
            }
        });

        jLabel3.setText("Apellido Materno:");

        campoApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoApellidoMaternoKeyTyped(evt);
            }
        });

        jLabel4.setText("Boleta:");

        campoBoleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBoletaKeyTyped(evt);
            }
        });

        jLabel5.setText("Carrera:");

        comboBoxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISISA", "INGENIERIA BIÓNICA", "INGENIERIA MECATRÓNICA", "INGENIERIA TELEMÁTICA" }));

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoApellidoPaterno)
                            .addComponent(campoApellidoMaterno)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboBoxCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton1))
                        .addGap(0, 896, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alumno", jPanel1);

        jLabel6.setText("Unidad de Aprendizaje:");

        jLabel7.setText("Academia: ");

        jButton2.setText("Insertar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Carrera:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoUnidadDeAprendizaje)
                            .addComponent(comboBoxAcademia, 0, 999, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(108, 108, 108)
                        .addComponent(comboBoxCarreras2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoUnidadDeAprendizaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboBoxCarreras2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Programa Académico", jPanel2);

        jLabel8.setText("Alumnos de Biónica:");

        labelBionicos.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelBionicos.setText("jLabel9");

        jLabel10.setText("Alumnos de Mecatrónica:");

        labelMecatronicos.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelMecatronicos.setText("jLabel11");

        jLabel12.setText("Alumnos de Telemática:");

        labelTelematicos.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelTelematicos.setText("jLabel13");

        jButton3.setText("Exportar a Excel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        comboBoxConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Demanda por Programa Académico", "Demanda por Unidades de Aprendizaje", "Demanda por Unidad de Aprendizaje (filtrada por carrera)", "Demanda general en toda UPIITA"}));
        comboBoxConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxConsultaActionPerformed(evt);
            }
        });

        jLabel14.setText("Total:");

        labelTotal.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelTotal.setText("jLabel15");

        jLabel16.setText("Matrícula:");

        labelMatricula.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelMatricula.setText("jLabel17");

        jLabel18.setText("Participación:");

        labelPorcentaje.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelPorcentaje.setText("jLabel19");

        jLabel13.setText("Alumnos de ISISA:");

        labelISISA.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelISISA.setText("jLabel13");

        comboBoxDiscrimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDiscriminaActionPerformed(evt);
            }
        });

        comboBoxDiscrimina2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDiscrimina2ActionPerformed(evt);
            }
        });
        comboBoxDiscrimina2.setVisible(false);

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahba/refresh.png"))); // NOI18N
        botonActualizar.setText("Actualizar");
        botonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonActualizarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonActualizarMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonActualizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonActualizarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonActualizarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(botonActualizar))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelISISA)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelBionicos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMecatronicos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTelematicos, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelTotal))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelMatricula))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelPorcentaje)))))
                        .addGap(97, 97, 97)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxDiscrimina, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxDiscrimina2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(labelBionicos))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(labelMecatronicos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(labelTelematicos)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(labelTotal))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(labelMatricula))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(labelPorcentaje)))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(labelISISA))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDiscrimina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDiscrimina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(13, 13, 13))
        );

        jTabbedPane1.addTab("Estadísticas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMouseClicked
        // TODO add your handling code here:
        getStatics();
        
    }//GEN-LAST:event_botonActualizarMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(
            AccionesTablaAlumnoCursaMateria.insertaNuevaUnidadDeAprendizaje(
                campoUnidadDeAprendizaje.getText(),
                comboBoxCarreras2.getSelectedItem().toString(),
                comboBoxAcademia.getSelectedItem().toString()
            )){
                JOptionPane.showMessageDialog(this, "Nueva carrera insertada con éxito!");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo ingresar la carrera");
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ah = AccionesTablaAlumnoCursaMateria.insertaAlumno(
            campoNombre.getText(),
            campoApellidoPaterno.getText(),
            campoApellidoMaterno.getText(),
            campoBoleta.getText(),
            comboBoxCarrera.getSelectedItem().toString()
        );
        System.out.println("ah: " + ah);
        switch (ah) {
            case 0:
            JOptionPane.showMessageDialog(this, "No pudo darse de alta correctamente");
            break;
            default:
            JOptionPane.showMessageDialog(this, "Dado de alta correctamente");
            campoNombre.setText(null);
            campoApellidoPaterno.setText(null);
            campoApellidoMaterno.setText(null);
            campoBoleta.setText(null);
            break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoBoletaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBoletaKeyTyped
        toUpper(evt);
    }//GEN-LAST:event_campoBoletaKeyTyped

    private void campoApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoApellidoMaternoKeyTyped
        toUpper(evt);
    }//GEN-LAST:event_campoApellidoMaternoKeyTyped

    private void campoApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoApellidoPaternoKeyTyped
        toUpper(evt);
    }//GEN-LAST:event_campoApellidoPaternoKeyTyped

    private void campoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyTyped
        toUpper(evt);
    }//GEN-LAST:event_campoNombreKeyTyped

    private void comboBoxConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxConsultaActionPerformed
        // TODO add your handling code here:
        switch(comboBoxConsulta.getSelectedIndex()){
            case 0:
                //Consultar en general
                comboBoxDiscrimina.setVisible(true);
                comboBoxDiscrimina2.setVisible(false);
                comboBoxDiscrimina.setModel(new DefaultComboBoxModel(AccionesTablaAlumnoCursaMateria.getListaCarreras()));
                comboBoxDiscrimina2.setModel(new DefaultComboBoxModel());
                break;
                
            case 1:
                comboBoxDiscrimina.setVisible(true);
                comboBoxDiscrimina2.setVisible(false);
                comboBoxDiscrimina.setModel(new DefaultComboBoxModel(AccionesTablaAlumnoCursaMateria.getListaMaterias()));
                comboBoxDiscrimina2.setModel(new DefaultComboBoxModel());
                break;
                
            case 2:
                comboBoxDiscrimina.setVisible(true);
                comboBoxDiscrimina.setModel(new DefaultComboBoxModel(AccionesTablaAlumnoCursaMateria.getListaCarreras()));
                comboBoxDiscrimina2.setVisible(true);
                comboBoxDiscrimina2.setModel(new DefaultComboBoxModel(AccionesTablaAlumnoCursaMateria.getListaMaterias(comboBoxDiscrimina.getSelectedItem().toString())));
                break;
                
            case 3:
                comboBoxDiscrimina.setVisible(false);
                comboBoxDiscrimina2.setVisible(false);
                data = AccionesTablaAlumnoCursaMateria.getConsultaGeneral(jScrollPane2);
                break;
                /*
            case 4:
                comboBoxDiscrimina.setVisible(true);
                comboBoxDiscrimina2.setVisible(false);
                comboBoxDiscrimina.setModel(new DefaultComboBoxModel(AccionesTablaAlumnoCursaMateria.getListaAcademias()));
                comboBoxDiscrimina2.setModel(new DefaultComboBoxModel());
                break;
                */
        }
    }//GEN-LAST:event_comboBoxConsultaActionPerformed

    private void comboBoxDiscriminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDiscriminaActionPerformed
        String item = comboBoxDiscrimina.getSelectedItem().toString();
        
        switch(comboBoxConsulta.getSelectedIndex()){
            case 0:
                //carrera
                data = AccionesTablaAlumnoCursaMateria.getConsultaPorCarrera(item, jScrollPane2);
                break;
                
            case 1:
                //academia
                data = AccionesTablaAlumnoCursaMateria.getConsultaPorMateria(item, jScrollPane2);
                break;
                
            case 4:
                data = AccionesTablaAlumnoCursaMateria.getConsultaPorAcademia(item, jScrollPane2);
            default:
                //materia
                comboBoxDiscrimina2.setModel(new DefaultComboBoxModel(AccionesTablaAlumnoCursaMateria.getListaMaterias(comboBoxDiscrimina.getSelectedItem().toString())));
                
                break;        
        }
        
        
    }//GEN-LAST:event_comboBoxDiscriminaActionPerformed

    private void comboBoxDiscrimina2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDiscrimina2ActionPerformed
        // TODO add your handling code here:
        String item = comboBoxDiscrimina2.getSelectedItem().toString();
        ModelTabla model;
        
        if(comboBoxConsulta.getSelectedIndex() == 2){
            data = AccionesTablaAlumnoCursaMateria.getConsultaPorMateriaDePrograma(comboBoxDiscrimina.getSelectedItem().toString(), item, jScrollPane2);
        }
    }//GEN-LAST:event_comboBoxDiscrimina2ActionPerformed

    private void botonActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMouseEntered
        // TODO add your handling code here:
        jPanel4.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_botonActualizarMouseEntered

    private void botonActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMouseExited
        // TODO add your handling code here:
        jPanel4.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_botonActualizarMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        CrearExcel ce = new CrearExcel(data);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMousePressed
        // TODO add your handling code here:
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_botonActualizarMousePressed

    private void botonActualizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMouseReleased
        // TODO add your handling code here:
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_botonActualizarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        if(args.length == 1){
            try{
                ExpedirQueries.exportAlumnosParticipantes("Tuka.csv");
            }catch(SQLException | IOException e){
                e.printStackTrace();
            }
            System.out.println("Done");
        }else{
        /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Alta().setVisible(true);
                }
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonActualizar;
    private javax.swing.JTextField campoApellidoMaterno;
    private javax.swing.JTextField campoApellidoPaterno;
    private javax.swing.JTextField campoBoleta;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoUnidadDeAprendizaje;
    private javax.swing.JComboBox<String> comboBoxAcademia;
    private javax.swing.JComboBox<String> comboBoxCarrera;
    private javax.swing.JComboBox comboBoxCarreras2;
    private javax.swing.JComboBox<String> comboBoxConsulta;
    private javax.swing.JComboBox comboBoxDiscrimina;
    private javax.swing.JComboBox comboBoxDiscrimina2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelBionicos;
    private javax.swing.JLabel labelISISA;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelMecatronicos;
    private javax.swing.JLabel labelPorcentaje;
    private javax.swing.JLabel labelTelematicos;
    private javax.swing.JLabel labelTotal;
    // End of variables declaration//GEN-END:variables

    private void toUpper(KeyEvent evt){
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }

    private void getStatics(){
        int bp, bm, mp, mm, tp, tm, ip, im;
        bp = AccionesTablaAlumnoCursaMateria.getParticipantes(AccionesTablaAlumnoCursaMateria.BIO);
        bm = AccionesTablaAlumnoCursaMateria.getMatricula(AccionesTablaAlumnoCursaMateria.BIO);
        mp = AccionesTablaAlumnoCursaMateria.getParticipantes(AccionesTablaAlumnoCursaMateria.MEC);
        mm = AccionesTablaAlumnoCursaMateria.getMatricula(AccionesTablaAlumnoCursaMateria.MEC);
        tp = AccionesTablaAlumnoCursaMateria.getParticipantes(AccionesTablaAlumnoCursaMateria.TEL);
        tm =AccionesTablaAlumnoCursaMateria.getMatricula(AccionesTablaAlumnoCursaMateria.TEL);
        ip = AccionesTablaAlumnoCursaMateria.getParticipantes(AccionesTablaAlumnoCursaMateria.ISISA);
        im = AccionesTablaAlumnoCursaMateria.getMatricula(AccionesTablaAlumnoCursaMateria.ISISA);
        labelBionicos.setText(
                String.valueOf(bp)
                        + " de " + String.valueOf(bm)
                        + " (%" + String.format("%.2f", ( bp * 100.0 ) / bm) 
                        + ")");
        labelMecatronicos.setText(
                String.valueOf(mp) 
                        + " de " + String.valueOf(mm)
                        + " (%" + String.format("%.2f", ( mp * 100.0 ) / mm) 
                        + ")");
        labelTelematicos.setText(
                String.valueOf(tp)
                        + " de " + String.valueOf(tm)
                        + " (%" + String.format("%.2f", ( tp * 100.0 ) / tm) 
                        + ")");
        labelISISA.setText(
                String.valueOf(ip)
                        + " de " + String.valueOf(im)
                        + " (%" + String.format("%.2f", ( ip * 100.0 ) / im) 
                        + ")");
        int t = AccionesTablaAlumnoCursaMateria.getParticipantes("todos");
        int m = AccionesTablaAlumnoCursaMateria.getMatricula("todos");
        labelTotal.setText(String.valueOf(t));
        labelMatricula.setText(String.valueOf(m));
        if(m == 0)
            m= 1;
        double p = (t * 100.0) / m;
        labelPorcentaje.setText("%" + String.format("%.2f", p));
        
    }

    
}
